// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminSidebarController from "./admin_sidebar_controller"
application.register("admin-sidebar", AdminSidebarController)

import DisableEnterController from "./disable_enter_controller"
application.register("disable-enter", DisableEnterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PricePreviewController from "./price_preview_controller"
application.register("price-preview", PricePreviewController)

import RecipeItemsController from "./recipe_items_controller"
application.register("recipe-items", RecipeItemsController)

import TableFilterController from "./table_filter_controller"
application.register("table-filter", TableFilterController)

import TrixNoAttachmentsController from "./trix_no_attachments_controller"
application.register("trix-no-attachments", TrixNoAttachmentsController)

import StockThresholdModalController from "./stock_threshold_modal_controller"
application.register("stock-threshold-modal", StockThresholdModalController)